// Country names for the signup country picker. Kept as a plain list (self-
// reported, stored as-is) — a common subset covering the vast majority of
// users; "Other" catches the rest.
export const COUNTRIES: string[] = [
  "United States",
  "United Kingdom",
  "Canada",
  "Australia",
  "Ireland",
  "New Zealand",
  "Germany",
  "France",
  "Spain",
  "Portugal",
  "Italy",
  "Netherlands",
  "Belgium",
  "Switzerland",
  "Austria",
  "Sweden",
  "Norway",
  "Denmark",
  "Finland",
  "Poland",
  "Czechia",
  "Greece",
  "Cyprus",
  "Malta",
  "Romania",
  "Bulgaria",
  "Hungary",
  "Croatia",
  "Serbia",
  "Ukraine",
  "Turkey",
  "Russia",
  "United Arab Emirates",
  "Saudi Arabia",
  "Israel",
  "India",
  "Pakistan",
  "Bangladesh",
  "China",
  "Japan",
  "South Korea",
  "Philippines",
  "Indonesia",
  "Malaysia",
  "Singapore",
  "Thailand",
  "Vietnam",
  "Mexico",
  "Brazil",
  "Argentina",
  "Chile",
  "Colombia",
  "Peru",
  "South Africa",
  "Nigeria",
  "Kenya",
  "Ghana",
  "Egypt",
  "Morocco",
  "Other",
];
