-- Blitz.tips demo seed data
-- Paste this whole file into Neon's SQL Editor and click Run.
-- Safe to re-run: existing rows are skipped via ON CONFLICT DO NOTHING.
-- All demo accounts log in with password: password123

BEGIN;

-- Sharp Steve
INSERT INTO "User" ("id","name","email","passwordHash","role","createdAt","updatedAt") VALUES ('u_sharpsteve', 'Sharp Steve', 'sharpsteve@blitz.tips', '$2b$12$jpk9C520UQA9ipRTLm9uceDWk5ghZ.VTaGljzeLZgRsBn32vVTwY2', 'HANDICAPPER', NOW(), NOW()) ON CONFLICT ("email") DO NOTHING;
INSERT INTO "HandicapperProfile" ("id","userId","handle","displayName","bio","sports","isVerified","monthlyPriceCents","createdAt","updatedAt") VALUES ('h_sharpsteve', 'u_sharpsteve', 'sharpsteve', 'Sharp Steve', 'Former line manager turned full-time NFL and NBA handicapper. Numbers over narratives.', ARRAY['NFL','NBA']::"PickSport"[], true, 4999, NOW(), NOW()) ON CONFLICT ("handle") DO NOTHING;
INSERT INTO "Pick" ("id","handicapperId","sport","league","matchup","betType","selection","odds","units","analysis","result","isPremium","eventStartsAt","settledAt","createdAt","updatedAt") VALUES ('p_sharpsteve_0', 'h_sharpsteve', 'NFL', 'NFL', 'Chiefs @ Bills', 'SPREAD', 'Bills -2.5', -110, 2, 'Bills defense has dominated at home this month.', 'WIN', true, NOW() - INTERVAL '20 days', NOW() - INTERVAL '20 days', NOW() - INTERVAL '20 days', NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "Pick" ("id","handicapperId","sport","league","matchup","betType","selection","odds","units","analysis","result","isPremium","eventStartsAt","settledAt","createdAt","updatedAt") VALUES ('p_sharpsteve_1', 'h_sharpsteve', 'NFL', 'NFL', 'Cowboys @ Eagles', 'TOTAL', 'Under 47.5', -108, 1.5, NULL, 'WIN', true, NOW() - INTERVAL '18 days', NOW() - INTERVAL '18 days', NOW() - INTERVAL '18 days', NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "Pick" ("id","handicapperId","sport","league","matchup","betType","selection","odds","units","analysis","result","isPremium","eventStartsAt","settledAt","createdAt","updatedAt") VALUES ('p_sharpsteve_2', 'h_sharpsteve', 'NFL', 'NFL', '49ers @ Rams', 'MONEYLINE', '49ers ML', -145, 3, NULL, 'LOSS', true, NOW() - INTERVAL '16 days', NOW() - INTERVAL '16 days', NOW() - INTERVAL '16 days', NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "Pick" ("id","handicapperId","sport","league","matchup","betType","selection","odds","units","analysis","result","isPremium","eventStartsAt","settledAt","createdAt","updatedAt") VALUES ('p_sharpsteve_3', 'h_sharpsteve', 'NBA', 'NBA', 'Celtics @ Bucks', 'SPREAD', 'Celtics -4', -112, 2, NULL, 'WIN', true, NOW() - INTERVAL '14 days', NOW() - INTERVAL '14 days', NOW() - INTERVAL '14 days', NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "Pick" ("id","handicapperId","sport","league","matchup","betType","selection","odds","units","analysis","result","isPremium","eventStartsAt","settledAt","createdAt","updatedAt") VALUES ('p_sharpsteve_4', 'h_sharpsteve', 'NBA', 'NBA', 'Nuggets @ Suns', 'TOTAL', 'Over 228.5', -105, 1, NULL, 'LOSS', true, NOW() - INTERVAL '12 days', NOW() - INTERVAL '12 days', NOW() - INTERVAL '12 days', NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "Pick" ("id","handicapperId","sport","league","matchup","betType","selection","odds","units","analysis","result","isPremium","eventStartsAt","settledAt","createdAt","updatedAt") VALUES ('p_sharpsteve_5', 'h_sharpsteve', 'NFL', 'NFL', 'Ravens @ Steelers', 'SPREAD', 'Ravens -3', -110, 2, NULL, 'WIN', true, NOW() - INTERVAL '10 days', NOW() - INTERVAL '10 days', NOW() - INTERVAL '10 days', NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "Pick" ("id","handicapperId","sport","league","matchup","betType","selection","odds","units","analysis","result","isPremium","eventStartsAt","settledAt","createdAt","updatedAt") VALUES ('p_sharpsteve_6', 'h_sharpsteve', 'NBA', 'NBA', 'Warriors @ Lakers', 'MONEYLINE', 'Lakers ML', 128, 1.5, NULL, 'WIN', true, NOW() - INTERVAL '8 days', NOW() - INTERVAL '8 days', NOW() - INTERVAL '8 days', NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "Pick" ("id","handicapperId","sport","league","matchup","betType","selection","odds","units","analysis","result","isPremium","eventStartsAt","settledAt","createdAt","updatedAt") VALUES ('p_sharpsteve_7', 'h_sharpsteve', 'NFL', 'NFL', 'Dolphins @ Jets', 'TOTAL', 'Under 41.5', -110, 1, NULL, 'PUSH', true, NOW() - INTERVAL '6 days', NOW() - INTERVAL '6 days', NOW() - INTERVAL '6 days', NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "Pick" ("id","handicapperId","sport","league","matchup","betType","selection","odds","units","analysis","result","isPremium","eventStartsAt","settledAt","createdAt","updatedAt") VALUES ('p_sharpsteve_8', 'h_sharpsteve', 'NBA', 'NBA', 'Heat @ Knicks', 'SPREAD', 'Knicks -6.5', -110, 2, NULL, 'WIN', true, NOW() - INTERVAL '4 days', NOW() - INTERVAL '4 days', NOW() - INTERVAL '4 days', NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "Pick" ("id","handicapperId","sport","league","matchup","betType","selection","odds","units","analysis","result","isPremium","eventStartsAt","settledAt","createdAt","updatedAt") VALUES ('p_sharpsteve_9', 'h_sharpsteve', 'NFL', 'NFL', 'Bengals @ Browns', 'MONEYLINE', 'Bengals ML', -160, 3, NULL, 'PENDING', true, NOW() - INTERVAL '0 days', NULL, NOW() - INTERVAL '0 days', NOW()) ON CONFLICT ("id") DO NOTHING;

-- Puck Queen
INSERT INTO "User" ("id","name","email","passwordHash","role","createdAt","updatedAt") VALUES ('u_puckqueen', 'Puck Queen', 'puckqueen@blitz.tips', '$2b$12$jpk9C520UQA9ipRTLm9uceDWk5ghZ.VTaGljzeLZgRsBn32vVTwY2', 'HANDICAPPER', NOW(), NOW()) ON CONFLICT ("email") DO NOTHING;
INSERT INTO "HandicapperProfile" ("id","userId","handle","displayName","bio","sports","isVerified","monthlyPriceCents","createdAt","updatedAt") VALUES ('h_puckqueen', 'u_puckqueen', 'puckqueen', 'Puck Queen', 'NHL specialist. I watch every game so you don''t have to.', ARRAY['NHL']::"PickSport"[], true, 3499, NOW(), NOW()) ON CONFLICT ("handle") DO NOTHING;
INSERT INTO "Pick" ("id","handicapperId","sport","league","matchup","betType","selection","odds","units","analysis","result","isPremium","eventStartsAt","settledAt","createdAt","updatedAt") VALUES ('p_puckqueen_0', 'h_puckqueen', 'NHL', 'NHL', 'Oilers @ Avalanche', 'MONEYLINE', 'Avalanche ML', -135, 2, NULL, 'WIN', true, NOW() - INTERVAL '22 days', NOW() - INTERVAL '22 days', NOW() - INTERVAL '22 days', NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "Pick" ("id","handicapperId","sport","league","matchup","betType","selection","odds","units","analysis","result","isPremium","eventStartsAt","settledAt","createdAt","updatedAt") VALUES ('p_puckqueen_1', 'h_puckqueen', 'NHL', 'NHL', 'Rangers @ Bruins', 'TOTAL', 'Over 5.5', -115, 1, NULL, 'LOSS', true, NOW() - INTERVAL '19 days', NOW() - INTERVAL '19 days', NOW() - INTERVAL '19 days', NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "Pick" ("id","handicapperId","sport","league","matchup","betType","selection","odds","units","analysis","result","isPremium","eventStartsAt","settledAt","createdAt","updatedAt") VALUES ('p_puckqueen_2', 'h_puckqueen', 'NHL', 'NHL', 'Panthers @ Maple Leafs', 'SPREAD', 'Panthers +1.5', -180, 3, NULL, 'WIN', true, NOW() - INTERVAL '15 days', NOW() - INTERVAL '15 days', NOW() - INTERVAL '15 days', NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "Pick" ("id","handicapperId","sport","league","matchup","betType","selection","odds","units","analysis","result","isPremium","eventStartsAt","settledAt","createdAt","updatedAt") VALUES ('p_puckqueen_3', 'h_puckqueen', 'NHL', 'NHL', 'Stars @ Golden Knights', 'MONEYLINE', 'Stars ML', 118, 1.5, NULL, 'WIN', true, NOW() - INTERVAL '11 days', NOW() - INTERVAL '11 days', NOW() - INTERVAL '11 days', NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "Pick" ("id","handicapperId","sport","league","matchup","betType","selection","odds","units","analysis","result","isPremium","eventStartsAt","settledAt","createdAt","updatedAt") VALUES ('p_puckqueen_4', 'h_puckqueen', 'NHL', 'NHL', 'Devils @ Islanders', 'TOTAL', 'Under 6', -105, 1, NULL, 'LOSS', true, NOW() - INTERVAL '7 days', NOW() - INTERVAL '7 days', NOW() - INTERVAL '7 days', NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "Pick" ("id","handicapperId","sport","league","matchup","betType","selection","odds","units","analysis","result","isPremium","eventStartsAt","settledAt","createdAt","updatedAt") VALUES ('p_puckqueen_5', 'h_puckqueen', 'NHL', 'NHL', 'Kraken @ Canucks', 'SPREAD', 'Canucks -1.5', 145, 1, NULL, 'WIN', true, NOW() - INTERVAL '3 days', NOW() - INTERVAL '3 days', NOW() - INTERVAL '3 days', NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "Pick" ("id","handicapperId","sport","league","matchup","betType","selection","odds","units","analysis","result","isPremium","eventStartsAt","settledAt","createdAt","updatedAt") VALUES ('p_puckqueen_6', 'h_puckqueen', 'NHL', 'NHL', 'Jets @ Wild', 'MONEYLINE', 'Jets ML', -125, 2, NULL, 'PENDING', true, NOW() - INTERVAL '0 days', NULL, NOW() - INTERVAL '0 days', NOW()) ON CONFLICT ("id") DO NOTHING;

-- Diamond King
INSERT INTO "User" ("id","name","email","passwordHash","role","createdAt","updatedAt") VALUES ('u_diamondking', 'Diamond King', 'diamondking@blitz.tips', '$2b$12$jpk9C520UQA9ipRTLm9uceDWk5ghZ.VTaGljzeLZgRsBn32vVTwY2', 'HANDICAPPER', NOW(), NOW()) ON CONFLICT ("email") DO NOTHING;
INSERT INTO "HandicapperProfile" ("id","userId","handle","displayName","bio","sports","isVerified","monthlyPriceCents","createdAt","updatedAt") VALUES ('h_diamondking', 'u_diamondking', 'diamondking', 'Diamond King', 'MLB run lines, totals, and first-five props. Grinding every day of the season.', ARRAY['MLB']::"PickSport"[], false, 2999, NOW(), NOW()) ON CONFLICT ("handle") DO NOTHING;
INSERT INTO "Pick" ("id","handicapperId","sport","league","matchup","betType","selection","odds","units","analysis","result","isPremium","eventStartsAt","settledAt","createdAt","updatedAt") VALUES ('p_diamondking_0', 'h_diamondking', 'MLB', 'MLB', 'Yankees @ Red Sox', 'MONEYLINE', 'Yankees ML', -150, 3, NULL, 'LOSS', true, NOW() - INTERVAL '25 days', NOW() - INTERVAL '25 days', NOW() - INTERVAL '25 days', NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "Pick" ("id","handicapperId","sport","league","matchup","betType","selection","odds","units","analysis","result","isPremium","eventStartsAt","settledAt","createdAt","updatedAt") VALUES ('p_diamondking_1', 'h_diamondking', 'MLB', 'MLB', 'Dodgers @ Giants', 'SPREAD', 'Dodgers -1.5', 135, 1, NULL, 'WIN', true, NOW() - INTERVAL '21 days', NOW() - INTERVAL '21 days', NOW() - INTERVAL '21 days', NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "Pick" ("id","handicapperId","sport","league","matchup","betType","selection","odds","units","analysis","result","isPremium","eventStartsAt","settledAt","createdAt","updatedAt") VALUES ('p_diamondking_2', 'h_diamondking', 'MLB', 'MLB', 'Astros @ Rangers', 'TOTAL', 'Under 8.5', -110, 1.5, NULL, 'WIN', true, NOW() - INTERVAL '17 days', NOW() - INTERVAL '17 days', NOW() - INTERVAL '17 days', NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "Pick" ("id","handicapperId","sport","league","matchup","betType","selection","odds","units","analysis","result","isPremium","eventStartsAt","settledAt","createdAt","updatedAt") VALUES ('p_diamondking_3', 'h_diamondking', 'MLB', 'MLB', 'Braves @ Mets', 'MONEYLINE', 'Braves ML', -120, 2, NULL, 'WIN', true, NOW() - INTERVAL '13 days', NOW() - INTERVAL '13 days', NOW() - INTERVAL '13 days', NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "Pick" ("id","handicapperId","sport","league","matchup","betType","selection","odds","units","analysis","result","isPremium","eventStartsAt","settledAt","createdAt","updatedAt") VALUES ('p_diamondking_4', 'h_diamondking', 'MLB', 'MLB', 'Orioles @ Blue Jays', 'TOTAL', 'Over 9', -105, 1, NULL, 'LOSS', true, NOW() - INTERVAL '9 days', NOW() - INTERVAL '9 days', NOW() - INTERVAL '9 days', NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "Pick" ("id","handicapperId","sport","league","matchup","betType","selection","odds","units","analysis","result","isPremium","eventStartsAt","settledAt","createdAt","updatedAt") VALUES ('p_diamondking_5', 'h_diamondking', 'MLB', 'MLB', 'Phillies @ Padres', 'SPREAD', 'Phillies -1.5', 150, 1, NULL, 'WIN', true, NOW() - INTERVAL '5 days', NOW() - INTERVAL '5 days', NOW() - INTERVAL '5 days', NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "Pick" ("id","handicapperId","sport","league","matchup","betType","selection","odds","units","analysis","result","isPremium","eventStartsAt","settledAt","createdAt","updatedAt") VALUES ('p_diamondking_6', 'h_diamondking', 'MLB', 'MLB', 'Cubs @ Cardinals', 'MONEYLINE', 'Cubs ML', 105, 1.5, NULL, 'PENDING', false, NOW() - INTERVAL '0 days', NULL, NOW() - INTERVAL '0 days', NOW()) ON CONFLICT ("id") DO NOTHING;

-- Rough Rider
INSERT INTO "User" ("id","name","email","passwordHash","role","createdAt","updatedAt") VALUES ('u_roughrider', 'Rough Rider', 'roughrider@blitz.tips', '$2b$12$jpk9C520UQA9ipRTLm9uceDWk5ghZ.VTaGljzeLZgRsBn32vVTwY2', 'HANDICAPPER', NOW(), NOW()) ON CONFLICT ("email") DO NOTHING;
INSERT INTO "HandicapperProfile" ("id","userId","handle","displayName","bio","sports","isVerified","monthlyPriceCents","createdAt","updatedAt") VALUES ('h_roughrider', 'u_roughrider', 'roughrider', 'Rough Rider', 'Newer to the platform, building a track record in college football.', ARRAY['NCAAF']::"PickSport"[], false, 1999, NOW(), NOW()) ON CONFLICT ("handle") DO NOTHING;
INSERT INTO "Pick" ("id","handicapperId","sport","league","matchup","betType","selection","odds","units","analysis","result","isPremium","eventStartsAt","settledAt","createdAt","updatedAt") VALUES ('p_roughrider_0', 'h_roughrider', 'NCAAF', 'NCAAF', 'Georgia @ Alabama', 'SPREAD', 'Alabama +3', -110, 2, NULL, 'LOSS', true, NOW() - INTERVAL '12 days', NOW() - INTERVAL '12 days', NOW() - INTERVAL '12 days', NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "Pick" ("id","handicapperId","sport","league","matchup","betType","selection","odds","units","analysis","result","isPremium","eventStartsAt","settledAt","createdAt","updatedAt") VALUES ('p_roughrider_1', 'h_roughrider', 'NCAAF', 'NCAAF', 'Ohio State @ Michigan', 'TOTAL', 'Under 44.5', -108, 1, NULL, 'LOSS', true, NOW() - INTERVAL '8 days', NOW() - INTERVAL '8 days', NOW() - INTERVAL '8 days', NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "Pick" ("id","handicapperId","sport","league","matchup","betType","selection","odds","units","analysis","result","isPremium","eventStartsAt","settledAt","createdAt","updatedAt") VALUES ('p_roughrider_2', 'h_roughrider', 'NCAAF', 'NCAAF', 'Texas @ Oklahoma', 'MONEYLINE', 'Texas ML', -130, 2, NULL, 'WIN', true, NOW() - INTERVAL '4 days', NOW() - INTERVAL '4 days', NOW() - INTERVAL '4 days', NOW()) ON CONFLICT ("id") DO NOTHING;

-- Demo subscriber (subscribed to @sharpsteve)
INSERT INTO "User" ("id","name","email","passwordHash","role","createdAt","updatedAt") VALUES ('u_subscriber', 'Demo Subscriber', 'subscriber@blitz.tips', '$2b$12$jpk9C520UQA9ipRTLm9uceDWk5ghZ.VTaGljzeLZgRsBn32vVTwY2', 'SUBSCRIBER', NOW(), NOW()) ON CONFLICT ("email") DO NOTHING;
INSERT INTO "Subscription" ("id","subscriberId","handicapperId","status","currentPeriodEnd","createdAt","updatedAt") VALUES ('s_demo', 'u_subscriber', 'h_sharpsteve', 'ACTIVE', NOW() + INTERVAL '30 days', NOW(), NOW()) ON CONFLICT ("subscriberId","handicapperId") DO NOTHING;

COMMIT;
